# General
title: Davide De Pretto
description: >-
  Software and data engineer. Most comfortable with the Microsoft stack, but from a Mac. Minimalist, yet knowledge-hungry. He/him.

# About me
author: Davide De Pretto
email: davide@depretto.dev
url: https://depretto.dev
github_username:  dadepretto
instagram_username: dadepretto
linkedin_username: dadepretto
twitter_username: dadepretto

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      author: Davide De Pretto

# Baking cookies ;)
google_analytics: UA-197737305-1

# Site settings
theme: minima
show_excerpts: true
plugins:
  - jekyll-target-blank
  - jekyll-feed
  - jekyll-redirect-from
