# General
title: Clean SQL
description: >-
  Yet another blog on data engineering and software development, but better.
  I will post about software architecture, SQL Server, TypeScript, and C#.

# About me
author: Davide De Pretto
email: dadepretto@icloud.com
url: https://dadepretto.com
twitter_username: dadepretto
github_username:  dadepretto
linkedin_username: dadepretto
instagram_username: dadepretto

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      author: Davide De Pretto

# Baking cookies ;)
google_analytics: UA-197737305-1

# Site settings
theme: minima
