# General
title: Batteries Included
description: >-
  Yet another blog on data engineering and software development, but better.
  I will post about software architecture on SQL Server, NodeJS, and .NET 5.

# About me
author: Davide De Pretto
email: dadepretto@icloud.com
url: https://dadepretto.com
github_username:  dadepretto
instagram_username: dadepretto
linkedin_username: dadepretto
twitter_username: dadepretto

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      author: Davide De Pretto

# Baking cookies ;)
google_analytics: UA-197737305-1

# Site settings
theme: minima
show_excerpts: true
plugins:
  - jekyll-target-blank