# General
title: Davide's Blog
description: >-
  Just a blog about software and database development.
  I like software architecture, and write mainly in T-SQL, TypeScript and C#.

# About me
author: Davide De Pretto
email: dadepretto@icloud.com
url: https://dadepretto.com
twitter_username: dadepretto
github_username:  dadepretto
linkedin_username: dadepretto
instagram_username: dadepretto

# Baking cookies ;)
google_analytics: UA-197737305-1

# Site settings
theme: minima
