name: Tweet

on:
  push:
    branches: [ main ]
    # paths:
    # - '_posts/**'
  pull_request:
    branches: [ main ]
    # paths:
    # - '_posts/**'

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "📰 Hey folks, I've published a new article on my blog! 🥳\n Go check it out! 👇 http://dadepretto.com "
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
